"""add stripe billing fields to business

Revision ID: e449e31e7497
Revises: 6b3bf3c9bf24
Create Date: 2026-08-16 19:12:18.053587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e449e31e7497'
down_revision: Union[str, Sequence[str], None] = '6b3bf3c9bf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('businesses', sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('businesses', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('businesses', sa.Column('subscription_plan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('businesses', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_businesses_stripe_customer_id'), 'businesses', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_stripe_customer_id'), table_name='businesses')
    op.drop_column('businesses', 'current_period_end')
    op.drop_column('businesses', 'trial_ends_at')
    op.drop_column('businesses', 'subscription_plan')
    op.drop_column('businesses', 'subscription_status')
    op.drop_column('businesses', 'stripe_subscription_id')
    op.drop_column('businesses', 'stripe_customer_id')
    # ### end Alembic commands ###
